/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author LUCYLEONOR
 */
import clases.*;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cafetera c;

    public Principal() {
        initComponents();
        cmdAgregar.setEnabled(false);
        cmdLlenarCafetera.setEnabled(false);
        cmdServirTaza.setEnabled(false);
        cmdVaciarCafetera.setEnabled(false);
        txtAgregarCafe.setEditable(false);
        txtNumeroTazas.setEditable(false);
        txtCantidadCafe.setEditable(false);
        cmdMostrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmdServirTaza = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        txtCantidadCafe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroTazas = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cmdVaciarCafetera = new javax.swing.JButton();
        cmdLlenarCafetera = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdRestaurar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtCapacidadMaxima = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmdEstablecer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCapacidadActual = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtAgregarCafe = new javax.swing.JTextField();
        cmdAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cafetera");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Cafetera");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servir Taza", 2, 0, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Cantidad de Café");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        cmdServirTaza.setText("Servir Taza");
        cmdServirTaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdServirTazaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdServirTaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servir Taza", 2, 0, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Núm. Tazas");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, 20));

        jButton5.setText("Servir Taza");
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 230, 100));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servir Taza", 2, 0, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Núm. Tazas");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel6.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, 20));

        jButton6.setText("Servir Taza");
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servir Taza", 2, 0, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Núm. Tazas");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel7.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, 20));

        jButton7.setText("Servir Taza");
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 230, 100));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 230, 110));
        jPanel2.add(txtCantidadCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel8.setText("Núm. Tazas");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));
        jPanel2.add(txtNumeroTazas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 470, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", 2, 0, new java.awt.Font("Times New Roman", 0, 13))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdVaciarCafetera.setText("Vaciar Cafetera");
        cmdVaciarCafetera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVaciarCafeteraActionPerformed(evt);
            }
        });
        jPanel4.add(cmdVaciarCafetera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cmdLlenarCafetera.setText("Llenar Cafetera");
        cmdLlenarCafetera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarCafeteraActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenarCafetera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, -1));

        cmdRestaurar.setText("Restaurar");
        cmdRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestaurarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 170, 210));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Establecer Capacidad", 2, 0, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCapacidadMaxima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadMaximaKeyTyped(evt);
            }
        });
        jPanel8.add(txtCapacidadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 70, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel7.setText("Capacidad Maxima");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        cmdEstablecer.setText("Establecer");
        cmdEstablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEstablecerActionPerformed(evt);
            }
        });
        jPanel8.add(cmdEstablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Capacidad Actual");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txtCapacidadActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadActualKeyTyped(evt);
            }
        });
        jPanel8.add(txtCapacidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 70, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Cafe", 2, 0, new java.awt.Font("Times New Roman", 0, 13))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel9.setText("Agregar Cafe");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel3.add(txtAgregarCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 70, -1));

        cmdAgregar.setText("Agregar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 590));

        setSize(new java.awt.Dimension(581, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEstablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEstablecerActionPerformed

        
        if (txtCapacidadMaxima.getText().trim().isEmpty() && txtCapacidadActual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese los datos", "Error", 2);
            txtCapacidadMaxima.requestFocusInWindow();
        } else if (txtCapacidadMaxima.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese la capacidad maxima", "Error", 2);
            txtCapacidadMaxima.requestFocusInWindow();
        } else if (txtCapacidadActual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese la capacidad actual", "Error", 2);
            txtCapacidadActual.requestFocusInWindow();
        } else if (Integer.parseInt(txtCapacidadMaxima.getText()) == 0) {
            Helper.mensaje(this, "La capacidad maxima de la cafetera no puede ser 0", "Error", 2);
            txtCapacidadMaxima.requestFocusInWindow();
            txtCapacidadMaxima.selectAll();
        } else {

            int CapacidadM = 0, CapacidadA = 0, sw = 1;
            try {
            CapacidadM = Integer.parseInt(txtCapacidadMaxima.getText());
            CapacidadA = Integer.parseInt(txtCapacidadActual.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Ingrese un numero valido", "Error", 2);
                txtCapacidadMaxima.requestFocusInWindow();
                txtCapacidadMaxima.selectAll();
                sw = 0;
            }
            if (sw == 1) {
                c = new Cafetera(CapacidadM, CapacidadA);
                Helper.mensaje(this, "Capacidad establecida correctamente\nCapadidad Actual: " + c.getCantidadactual() + "\nCapacidad Maxima: " + c.getCapacidadMaxima(), "Capacidad", 1);
                txtCapacidadMaxima.setText("");
                txtCapacidadActual.setText("");
                cmdAgregar.setEnabled(true);
                cmdLlenarCafetera.setEnabled(true);
                cmdServirTaza.setEnabled(true);
                cmdVaciarCafetera.setEnabled(true);
                txtAgregarCafe.setEditable(true);
                txtNumeroTazas.setEditable(true);
                txtCantidadCafe.setEditable(true);
                txtCapacidadActual.setEditable(false);
                txtCapacidadMaxima.setEditable(false);
                cmdEstablecer.setEnabled(false);
                cmdMostrar.setEnabled(true);
                
            }

        }


    }//GEN-LAST:event_cmdEstablecerActionPerformed

    private void cmdServirTazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdServirTazaActionPerformed

        if (txtCantidadCafe.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese la cantidad de cafe", "Error", 2);
            txtCantidadCafe.requestFocusInWindow();
        } else if (txtNumeroTazas.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese el numero de tazas", "Error", 2);
            txtCantidadCafe.requestFocusInWindow();
        } else {
            int cantidadC = 0, sw = 1, cantidadT = 0, res;
            try {
                cantidadC = Integer.parseInt(txtCantidadCafe.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Ingrese un numero valido", "Error", 2);
                sw = 0;
                txtCantidadCafe.requestFocusInWindow();
                txtCantidadCafe.selectAll();
            }
            try {
                cantidadT = Integer.parseInt(txtNumeroTazas.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Ingrese un numero valido", "Error", 2);
                sw = 0;
                txtNumeroTazas.requestFocusInWindow();
                txtNumeroTazas.selectAll();
            }

            if (sw == 1) {
                if (c.getCantidadactual() == 0) {
                    Helper.mensaje(this, "No hay café", "Error", 2);
                    txtCantidadCafe.setText("");
                    txtNumeroTazas.setText("");
                } else if (c.getCantidadactual() < (cantidadC * cantidadT)) {
                    res = Helper.mensaje(this, "Solo queda " + c.getCantidadactual() + "\n¿Desea servir?", "Poca cantidad", 3);
                    if (res == 0) {
                        c.ServirTaza(cantidadT, cantidadC);
                        sw = 1;
                        txtCantidadCafe.setText("");
                        txtNumeroTazas.setText("");
                    } else {
                        sw = 0;
                    }
                
                } else {
                    c.ServirTaza(cantidadT, cantidadC);
                    Helper.mensaje(this, "Taza servida correctamente, su cantidad de café actual es: " + c.getCantidadactual(), "Taza Servida", 1);
                    txtCantidadCafe.setText("");
                    txtNumeroTazas.setText("");
                }
            }

        }
    }//GEN-LAST:event_cmdServirTazaActionPerformed

    private void cmdLlenarCafeteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarCafeteraActionPerformed
        c.LlenarCafetera();
        Helper.mensaje(this, "Capacidad establecida correctamente\nCapadidad Actual: " + c.getCantidadactual() + "\nCapacidad Maxima: " + c.getCapacidadMaxima(), "Capacidad", 1);
    }//GEN-LAST:event_cmdLlenarCafeteraActionPerformed

    private void cmdVaciarCafeteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVaciarCafeteraActionPerformed
        c.Vaciar();
        Helper.mensaje(this, "Cafetera vaciada correctamente, cantidad actual: " + c.getCantidadactual(), "Vaciar Cafetera", 1);
    }//GEN-LAST:event_cmdVaciarCafeteraActionPerformed

    private void txtCapacidadMaximaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadMaximaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtCapacidadMaximaKeyTyped

    private void txtCapacidadActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadActualKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtCapacidadActualKeyTyped

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed

        if (txtAgregarCafe.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese la cantidad de cafe", "Error", 2);
            txtAgregarCafe.requestFocusInWindow();
        } else {
            int AgregarC = 0, sw = 1,n;
            try {
                AgregarC = Integer.parseInt(txtAgregarCafe.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Ingrese un numero valido", "Error", 2);
                sw = 0;
                txtAgregarCafe.requestFocusInWindow();
                txtAgregarCafe.selectAll();
            }
            if (sw == 1) {
                if (c.getCantidadactual() == c.getCapacidadMaxima()) {
                    Helper.mensaje(this, "La capacidad actual esta al maximo", "Error", 2);
                    txtAgregarCafe.setText("");
                }
                else {
                c.AgregarCafe(AgregarC);
                Helper.mensaje(this, "su capacidad actual es:"+c.getCantidadactual(), "Café Agregado", 1);
                txtAgregarCafe.setText("");
                }
                }
            
        }
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        Helper.mensaje(this, "Capacidad Maxima: "+c.getCapacidadMaxima()+"\nCapacidad Actual: "+c.getCantidadactual(),"Mostrar",1);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestaurarActionPerformed
        txtNumeroTazas.setText("");
        txtAgregarCafe.setText("");
        txtCantidadCafe.setText("");
        txtCapacidadActual.setText("");
        txtCapacidadMaxima.setText("");
        cmdAgregar.setEnabled(false);
        cmdLlenarCafetera.setEnabled(false);
        cmdServirTaza.setEnabled(false);
        cmdVaciarCafetera.setEnabled(false);
        txtAgregarCafe.setEditable(false);
        txtNumeroTazas.setEditable(false);
        txtCantidadCafe.setEditable(false);
        txtCapacidadMaxima.setEditable(true);
        txtCapacidadActual.setEditable(true);
        txtCapacidadMaxima.requestFocusInWindow();
        cmdEstablecer.setEnabled(true);
        cmdMostrar.setEnabled(false);
    }//GEN-LAST:event_cmdRestaurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdEstablecer;
    private javax.swing.JButton cmdLlenarCafetera;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRestaurar;
    private javax.swing.JButton cmdServirTaza;
    private javax.swing.JButton cmdVaciarCafetera;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtAgregarCafe;
    private javax.swing.JTextField txtCantidadCafe;
    private javax.swing.JTextField txtCapacidadActual;
    private javax.swing.JTextField txtCapacidadMaxima;
    private javax.swing.JTextField txtNumeroTazas;
    // End of variables declaration//GEN-END:variables
}
